on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
      
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install -y g++ cmake

    - name: Install Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/libgtest*.a /usr/lib/

    - name: Build and Test
      run: |
        g++ tests.cpp -lgtest -lpthread -o test
        ./test
